# Generated by Django 3.1.5 on 2021-01-24 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_auto_20210124_1732'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('question_text',)},
        ),
    ]
